# Generated by Django 5.2.8 on 2025-11-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('aulas', 'Aulas'), ('provas', 'Provas'), ('ciclos', 'Ciclos'), ('outros', 'Outros')], max_length=15),
        ),
    ]
